#Get all User

GET  http://localhost:9494/api/v1/employees HTTP/1.1

###

#Post a new user
POST http://localhost:9494/api/v1/employees HTTP/1.1
content-type: application/json

{
  "fistName": "Trọng",
  "lastName": "Hoàng Xuân",
  "email": "tronghx@gmail.com",
  "phoneNumber": "01234567890",
  "address": "Đà Nẵng",
  "birthDay": "1994-10-10",
  "password": "addw2rđa3s@",
  "photo": ""
}

###
DELETE   http://localhost:9494/api/v1/categories/2 HTTP/1.1


###
PATCH  http://localhost:9494/api/v1/employees/652571e6d0214e6b58ff4266 HTTP/1.1
content-type: application/json

{
    "PhoneNumber": "0986712124"
}